### ISSUE TITLE
Non-ASCII error when running main.py

### ISSUE THREAD

**Issue by ninnyyan1993** [daohu527/imap#1]
run 
`python main.py -m data/borregas_ave.txt`
got error
`File "main.py", line 23
SyntaxError: Non-ASCII character '\xc2' in file main.py on line 23, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

Need to add `# -*- coding: utf-8 -*` at the very beginning of script to solve this error.

**Comment by daohu527** [comment]
fix it
