### ISSUE TITLE
map format

### ISSUE THREAD

**Issue by jiaqi-lian** [daohu527/imap#103]
Hello, the apollo format generated by LGSVL is bin format, so how to convert to txt format, I look forward to your answer！

**Comment by jiaqi-lian** [comment]
Thank you very much for your reply

**Comment by jiaqi-lian** [comment]
I'm sorry to bother you again, but I've recently encountered a new problem, first, when I used Apollo's map_gen tool to generate a map into lgsvl, I encountered a problem under the map, please how should I solve it; Second, I would like to know if there is currently open source code generated in OpenDrive format based on CSV files, and I look forward to your response
![image](https://github.com/daohu527/imap/assets/73477780/aee3443c-9736-44dd-95ba-1e1cd96a7435)

**Comment by daohu527** [comment]
No, I don’t have any good suggestions at the moment
