### ISSUE TITLE
The broken line became a solid line

### ISSUE THREAD

**Issue by wujf1517** [daohu527/imap#106]
When converting from xodr format to Apollo format, the original broken line became a solid line, is there a way to change it to a dashed line？

**Comment by daohu527** [comment]
yes, but we'd better confirm the problem, such as the road type in opendrive

**Comment by wujf1517** [comment]
Thank you for your reply. My xodr file contains the type broken line. For a detailed map, see 'straight_line.xodr' on github: https://github.com/wujf1517/road_map.git. The conversion command I used was similar to the following:

imap -f -i data/town.xodr -o data/apollo_map.txt

**Comment by daohu527** [comment]
I will check and feedback soon

**Comment by zhanglonggao** [comment]
> I will check and feedback soon

I am facing the same issue, that the original broken line became a solid line. May I know if there have been any developments regarding this issue ?

**Comment by daohu527** [comment]
@wujf1517 @zhanglonggao 
imap use `roadmark_type` to generate road boundary type. And I found the xodr map don't have this field!

You can refer to the specification

https://publications.pages.asam.net/standards/ASAM_OpenDRIVE/ASAM_OpenDRIVE_Specification/latest/specification/13_objects/13_14_object_examples.html#_roadmark

**Comment by zhanglonggao** [comment]
> @wujf1517 @zhanglonggao imap use `roadmark_type` to generate road boundary type. And I found the xodr map don't have this field!
> 
> You can refer to the specification
> 
> https://publications.pages.asam.net/standards/ASAM_OpenDRIVE/ASAM_OpenDRIVE_Specification/latest/specification/13_objects/13_14_object_examples.html#_roadmark

OK , I got it, thank you for your reply
