### ISSUE TITLE
支持将bin格式转换成xml格式嘛

### ISSUE THREAD

**Issue by lsm2842035890** [daohu527/imap#110]

**Comment by daohu527** [comment]
@lsm2842035890 No, Apollo does not currently support the xml format. I don't know what the source of your demand is.

**Comment by MrGoldminer** [comment]
这会有方案了吗？

**Comment by daohu527** [comment]
@MrGoldminer I think a more accurate description is to convert **Apollo format to opendrive format map**？

**Comment by MrGoldminer** [comment]
这会还是没有方案

**Comment by 1012327963** [comment]
请问后续可以支持由apollo格式转化为opendrive的格式吗

**Comment by daohu527** [comment]
@1012327963 If many people have this need, I will add this feature!

**Comment by lov-cly** [comment]
作者大大，请添加这个功能，很需要！！！（恳求）

**Comment by daohu527** [comment]
I will create a design document first and then see how to start the project.

**Comment by daohu527** [comment]
Close it as we start work #112
