### ISSUE TITLE
opendrive地图转换成apollo的地图时出错

### ISSUE THREAD

**Issue by wycrystal** [daohu527/imap#16]
参考readme里运行样例是可以正常显示地图的。但是换成我用roadrunner导出的opendrive地图转换apollo的地图就报错了，见下图
![image](https://user-images.githubusercontent.com/81356719/158552183-c6fd9f30-cf6a-4c4a-9969-e5fd38340925.png)

麻烦帮忙看一下是什么原因？谢谢了！

**Comment by daohu527** [comment]
I have fixed the bug for missing dependency. #17 

What I want to remind is that roadrunner can directly export apollo format. imap still needs to work on some details, I plan to finish the lanes, intersections and traffic lights in March.

**Comment by wycrystal** [comment]
> 



> I have fixed the bug for missing dependency. #17
> 
> What I want to remind is that roadrunner can directly export apollo format. imap still needs to work on some details, I plan to finish the lanes, intersections and traffic lights in March.

按照回复修改了，但是运行的时候又出现了其它问题，如下图：

![image](https://user-images.githubusercontent.com/81356719/158748958-dd4498ff-1b72-485e-8ac3-17bfdedccde7.png)

**Comment by wycrystal** [comment]
我从roadrunner直接导出apollo的地图，然后再生成sim_map的时候报错了，你能帮我看一下吗？
![image](https://user-images.githubusercontent.com/81356719/158749410-31ad289a-ae11-4a88-94d2-1f5a097e019b.png)

**Comment by daohu527** [comment]
I have fixed the bug, if you still have bug then you can send me the xodr file by daohu527@gmail.com

## sim_map_generator
You can analyze the core dump file by below cmd and then find the reason.
```
gdb ./bazel-bin/modules/map/tools/sim_map_generator ./data/xxxx.core_dump
```

**Comment by daohu527** [comment]
This issue is closed due to not being active. Please feel free to open it again

**Comment by Gavin666Github** [comment]
> roadrunner直接导出apollo

大佬，roadrunner直接导出apollo，能帮忙导一个文件吗，roadrunner 怎么装上的呢，貌似收费
