### ISSUE TITLE
Virtual lane lines and maps

### ISSUE THREAD

**Issue by li123il** [daohu527/imap#40]
Hello, Mr. Wang. I'd like to ask if the opendrive format is used when generating the virtual lane line file TXT? When I read many articles, I introduced that the high-precision map of Apollo was changed in the format of opendrive. Does the high-precision map refer to virtual lane lines, traffic lights, pedestrian crossings and so on? Or is it a three-dimensional environment generated by lidar records?

**Comment by li123il** [comment]
I think the format of opendrive is different from that of virtual lane line

**Comment by daohu527** [comment]
I think you need to learn these 2 formats first, I'm not quite sure what your problem is

if your question is "if apollo hd-map different from opendrive".
Yes, there're quit different, the overall implementation is different, but the elements represented are consistent

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
