### ISSUE TITLE
格式转换失败

### ISSUE THREAD

**Issue by Forrest-Z** [daohu527/imap#41]
你好，我使用pip安装工具后，将按照readme中介绍，将opendrive的地图转apollo的txt地图时，没有输出结果，请问知道啥原因吗？执行输出为
/home/forrest/.local/lib/python3.8/site-packages/imap/lib/opendrive/profile.py:42: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if not raw_elevation_profile:
parse_geo_reference is +lat_0=4.9000000000000000e+1 +lon_0=8.0000000000000000e+0:

**Comment by daohu527** [comment]
There doesn't seem to be an error message, have you tried the file in the example?
you can try to convert [town.xodr](https://github.com/daohu527/imap/blob/main/imap/data/town.xodr) first.

**Comment by Forrest-Z** [comment]
我这边使用的就是[town.xodr](https://github.com/daohu527/imap/blob/main/imap/data/town.xodr)这个opendrive的地图，执行了imap -f -i data/town.xodr -o data/apollo_map.txt指令后，能把town.xodr显示出来，但是apollo_map.txt没有输出

**Comment by daohu527** [comment]
Can you check the permissions of the data directory
```
sudo chmod 777 -R data
```

**Comment by daohu527** [comment]
@Forrest-Z  Good job, looks like the program could be improved!
