### ISSUE TITLE
When I run the command there is an error

### ISSUE THREAD

**Issue by Mcwbiubiubiu** [daohu527/imap#42]
when i run the command(imap -m data/borregas_ave.txt) ,the error "Error: Cannot parse %s as binary or text proto data/borregas_ave.txt" come out .Also ,i see the code (/home/mcw/imap-main/imap/lib/proto_utils)。But I don't know what went wrong.

**Comment by daohu527** [comment]
I tested it and it works fine, be sure to use python3, could you pls add print some debug info, like below.
```
    try:
        return get_pb_from_bin_file(filename, pb_value)
    except:
        try:
            return get_pb_from_text_file(filename, pb_value)
        except:
            import traceback; traceback.print_exc()            # here is the debug code
            print('Error: Cannot parse %s as binary or text proto', filename)
```

**Comment by Mcwbiubiubiu** [comment]
Thanks,i will try soon and  tell you the result

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
