### ISSUE TITLE
Excuse, ask a question about hdmap

### ISSUE THREAD

**Issue by Mcwbiubiubiu** [daohu527/imap#43]
Excuse me, I would like to ask, is there any high precision map visualization currently done in C++? Do you have any relevant material to recommend? I only found a showmap tool in Apollo code, which is similar to your visualization method.

**Comment by daohu527** [comment]
The difficulty is not in the display, you can do it with `qt`

**Comment by Mcwbiubiubiu** [comment]
Yes, I just want to use qt to display hdmap, but i don't konw huo to do. I'm looking up information on this now. Can I add you a contact? For example, email or WeChat. Just for study.

**Comment by daohu527** [comment]
Seems out of scope for this project, I'll close this question for now!
