### ISSUE TITLE
how to use bin_map_generator to generator base_map.bin in Apollo?

### ISSUE THREAD

**Issue by zhuiyuehun** [daohu527/imap#47]
Hello DaoHu. I have a question and want to know why . Firstly, use carla_map(Town01.xodr) to genenrate a base_map.txt, and using  bin_map_generator to generate base_map.bin file in Apollo docker(R7.0.0). but dreamview can't show it  on web. can you tell why? Please

**Comment by zhuiyuehun** [comment]
Or map files generated by imap, not suitable for generating bin files？

**Comment by daohu527** [comment]
dreamview support both txt and bin format, you can easily use below cmd to convert them to each other.

```
source scripts/apollo_base.sh

protoc --decode apollo.hdmap.Map modules/map/proto/map.proto < base_map.bin > base_map.txt

protoc --encode apollo.hdmap.Map modules/map/proto/map.proto < base_map.txt > base_map.bin
```

**Comment by zhuiyuehun** [comment]
Very happy with the new feature update，and the problem still not solved。
I want to convert carla map to apollo map, the test process is as follows：
`imap -f -i Town01.xodr -o base_map.txt `
`./bazel-bin/modules/map/tools/bin_map_generator -base_map_filename=modules/map/data/carla_town01/base_map.txt output_dir=modules/map/data/carla_town01/base_map.bin
I0628 19:51:09.126901 21729 bin_map_generator.cc:42] []Loaded txt map from /apollo/modules/map/data/demo/base_map.txt
I0628 19:51:09.128259 21729 bin_map_generator.cc:55] []Successfully converted .txt map to .bin map: /tmp/base_map.bin`
but this base_map.bin can't show on this web [https://ntutangyun.github.io/apollo-hd-map-viewer/](url)
where did i go wrong？

**Comment by zhuiyuehun** [comment]
Dreamview does not display the map because of the lack of border_type elements，your advice is very useful！thank u.

**Comment by daohu527** [comment]
imap could also display the map, which use the center line to display but not the boundary.
