### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ckiller007** [daohu527/imap#48]
1  .\imap\lib\opendrive\map.py 文件中， 为road和junction添加 predecessor、successor信息时，应判断原始xx.xodr文件中对应的信息是否为空，如果为空，则跳过。  某些xx.xodr的信息不完整，如不判断，会产生找不到对应的元素的问题。
2  如果是carla脚本生成的xx.xodr的name有可能是乱码，如果不处理，会出现bug. 需可以增加相关的判断逻辑.
3.  建议在说明文件中明确运行环境和依赖版本。

**Comment by daohu527** [comment]
谢谢你的建议! 实际上，由于很多人不遵循标准，导致代码中会增加大量的判断，这很不优雅。虽然防御性编程可能可以解决这些问题，但这会让代码中充斥大量的判断，影响整体逻辑。因此我们要平衡，并且严格遵循规范。

运行环境可以直接通过pip安装，在setup.py文件中可以申明版本号
https://github.com/daohu527/imap/blob/1c7e4f7ca615dc49ffcd245ef9b081b24735072b/setup.py#L25-L29
