### ISSUE TITLE
xodr转apollo时，s值折叠.

### ISSUE THREAD

**Issue by ckiller007** [daohu527/imap#49]
例如: 直线和ParamPoly3相接，第一段是直线(直线长度非整数，例如33.45339495)，第二段是ParamPoly3(起始s=33.45339495)时:
            程序生成的结果是:
              left_sample {
                s: 34.0
                width: 2.0
              }
              left_sample {
                s: 33.45339495
                width: 2.0
              }
s:34为直线的最后一个点，s:33.4533是ParamPoly3的第一个点。
由于直线采样时，采样点数是向上取整，导致计算最后一个点的s的时候，absolute_s = self.s + s，s值会等于直线段长度向上取整。此时,ParamPoly3计算s的时候，会以自身起始s开始计算，例如s: 33.45339495，会导致生成的apollo地图的s值在交接处会部分重叠。

**Comment by daohu527** [comment]
是的，由于目前的采样间隔是1米，因此会出现这样的问题，实际上道路的前后节点可能需要一点overlap，这有待确认是否一定需要，或者是否合理。

这样的误差可能还好，可以在合理的范围之内，但是我注意到有一些曲线即使增加一点overlap也会产生非常大的数值，现象上就是曲线飞了很远，这个问题有待确认是不是上述原因引起的。

记下来，我们可能会尝试修复overlap，看下是否可行。

**Comment by daohu527** [comment]
我已经提交了修改，看下这样是否符合要求
