### ISSUE TITLE
imap convert xodr to txt ,but miss lane boundary_type

### ISSUE THREAD

**Issue by stanhua123** [daohu527/imap#55]
Hi ,I use imap to convert xodr to txt
but txt file don't have left and right lane boundary_type,which may casuse the map can not be shown in dreamview.

**Comment by daohu527** [comment]
@stanhua123 Fixed in imap 0.0.6, you can try `pip3 install imap-box -U` and feedback.

**Comment by stanhua123** [comment]
> @stanhua123 Fixed in imap 0.0.6, you can try `pip3 install imap-box -U` and feedback.

It works,thanks
