### ISSUE TITLE
生成异常

### ISSUE THREAD

**Issue by jiaqi-lian** [daohu527/imap#57]
您好，当我使用imap显示地图文件时出现：
D:\ProgramData\Anaconda3\lib\site-packages\imap\lib\proto_utils.py:68: RuntimeWarning: Unexpected end-group tag: Not all data was converted pb_value.ParseFromString(file_in.read())
 此地图文件是apollo中map_gen生成出来的文件，为什么会出现显示错误呢

**Comment by daohu527** [comment]
可能是你的文件格式不对，比如文件末尾有一些特殊字符

**Comment by jiaqi-lian** [comment]
```
(base) D:\JQwork\py\imap-main\imap-main\imap>python map_show.py -m data\map.txt         
D:\ProgramData\Anaconda3\lib\site-packages\imap\lib\proto_utils.py:68: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  pb_value.ParseFromString(file_in.read())
```
文件名为map.txt; 应该不是出问题的原因，想问一下您的apollo格式地图是apollo中map_gen生成的吗，我怀疑是txt文件的问题

**Comment by daohu527** [comment]
我就是说是你文件内容的问题

**Comment by jiaqi-lian** [comment]
感谢回复，我是用.bin文件显示成功了，确实可能txt文件内容存在问题
