### ISSUE TITLE
Add sampling for Poly3 and ParamPoly3 in plan_view.py

### ISSUE THREAD

**Issue by amazongs012** [daohu527/imap#59]
It will helps a lot.
Thanks a lot.

**Comment by amazongs012** [comment]
i complete the sampling for Poly3 and i will close this issue

**Comment by daohu527** [comment]
@amazongs012  That's great! Can you add instructions so I can add this functionality. I still don't understand how this sampling works

**Comment by amazongs012** [comment]
I send a pull request,you may check it
