### ISSUE TITLE
when convert xodr to apollo, in junction area, its boundary line will become distorted

### ISSUE THREAD

**Issue by amazongs012** [daohu527/imap#60]
![distorted_area](https://user-images.githubusercontent.com/57893216/201598878-64290ac5-1777-4a60-af4b-06f6deba6598.png)

xodr file was exported form VTD

**Comment by daohu527** [comment]
Because the sampling will be slightly extended, the above may occur.  Is the distance of the above intersection very short, for example around 2 meters?

**Comment by amazongs012** [comment]
the  of intersection is about 20 meters, and the width of road is about 7.5

**Comment by amazongs012** [comment]
I shorten the sample length to 0.5 meters, the problem still occurs

**Comment by daohu527** [comment]
Then maybe we need to debug to know where the problem is

**Comment by amazongs012** [comment]
i wonder maybe the last point of spiral part,  have too much error

**Comment by amazongs012** [comment]
but i didn't have a better way to solve it

**Comment by daohu527** [comment]
could you pls indicate which section is a spiral and which section is a straight line, for example use different color

**Comment by amazongs012** [comment]
![dispart_line](https://user-images.githubusercontent.com/57893216/202950504-f9575f3d-397c-4e08-bcfb-bc45fc453de5.png)
in this picture, the yellow line is straight line, blue line is spiral and red line is arc

**Comment by daohu527** [comment]
It looks like the lines don't connect, so is there something wrong with the map? Or is the calculation of the spiral wrong?

**Comment by amazongs012** [comment]
the map comes was exported from VTD,and i import the map to other tools to check, it was right .

At first, i think it may be the wrong calculate of arc,  but after i replace the way of calculation of arc, the problem still occurs,
so i guess the calculation of spiral may have some problem.

**Comment by amazongs012** [comment]
the lines don't connect is because i split the points to different parts
so the error calculated points(the point of spiral) could not connect to the line

**Comment by daohu527** [comment]
Straight lines are generally not wrong, so we need to confirm whether it is a problem with the spiral. 

The spiral algorithm was also ported from elsewhere, so I'm not sure if there is an error here

**Comment by amazongs012** [comment]
yeah, i still could not find where the error is , but after i replace the sampling code, it seems ok

**Comment by amazongs012** [comment]
![repair_line](https://user-images.githubusercontent.com/57893216/203236227-c8326906-33a1-43a7-a23e-66bb0da1880d.png)

just like the picture

**Comment by amazongs012** [comment]
and i will close this issue

**Comment by daohu527** [comment]
@amazongs012 good new! could you send the xodr file to me. And I will debug later!

**Comment by daohu527** [comment]
@amazongs012 I fixed the error, the error is due to the spiral, probably we need an initial angle.

**Comment by amazongs012** [comment]
thank you ,and the xodr was for test,  for study how to convert OD to Apollo @daohu527

**Comment by daohu527** [comment]
OK, thank you for your help!
