### ISSUE TITLE
question about Elevation

### ISSUE THREAD

**Issue by amazongs012** [daohu527/imap#61]
![get_Elevation_by_s](https://user-images.githubusercontent.com/57893216/202407561-78441613-352c-4d2c-a464-bd5557dbb7c3.png)

when i read the code about Elevation, i see some strange variable(like: "s"), could you please tell me the answer?
thanks a lot

**Comment by daohu527** [comment]
You can ref below pic, height varies with s
![image](https://user-images.githubusercontent.com/10419854/202473115-e4bf8032-f89a-48ca-90c8-16af0c20adfe.png)
