### ISSUE TITLE
when calculate each planview of road, get the cross line

### ISSUE THREAD

**Issue by amazongs012** [daohu527/imap#68]
![pic1](https://user-images.githubusercontent.com/57893216/206077004-32818743-ad42-4bd9-87eb-1598de4a6a2b.png)

in this picture, the turn before the junction, if enlarge view the turn, we can see this, like picture below

![pic2](https://user-images.githubusercontent.com/57893216/206077454-42e577f1-451d-4d54-b8da-d7c0bfc7bb16.png)

**Comment by amazongs012** [comment]
i might have know the reason:  the last few points of the pre planview, and the first few points may come to wrong position,
but i didn't know how to resolve it

**Comment by amazongs012** [comment]
You may ignore errors within the intersection,  i don't merge the lastest code into mine

**Comment by daohu527** [comment]
You can try the latest code and have a try then.

**Comment by amazongs012** [comment]
![error2](https://user-images.githubusercontent.com/57893216/206100752-c01c43ed-1ee4-480a-b808-f6c972b0472b.png)
 
it still occurs

**Comment by amazongs012** [comment]
this mistake might not the wrong calculation of arc and spiral,
the reason is just like i said :The last few points of the first part and the first few points of the second part are intersected

**Comment by daohu527** [comment]
We do oversample some distance, but that's only 1m, so are you sure that's going to affect a lot. you can use `-s=0.1` which you can set the sample length to 0.1m
