### ISSUE TITLE
the lastest code i download could't run directly

### ISSUE THREAD

**Issue by amazongs012** [daohu527/imap#69]
![error1](https://user-images.githubusercontent.com/57893216/206082788-eaa47541-a99d-4fbd-9b76-ff72978eabd6.png)

it could't find a variables

**Comment by daohu527** [comment]
Maybe you modified imap and forgot to include https://github.com/daohu527/imap/blob/main/imap/global_var.py

**Comment by amazongs012** [comment]
No, i just download this code and run
