### ISSUE TITLE
How to deal with the map when the number of lanes changed

### ISSUE THREAD

**Issue by treenewbee213** [daohu527/imap#73]
![image](https://user-images.githubusercontent.com/58296268/220586404-8e50e9dc-c167-4ff5-9b35-e71225eb89e3.png)
When the number of lanes in the adjacent section changes，how to deal with the map？For example, this is the case in the picture，the only way to deal with the case is to transform them into junction？

**Comment by daohu527** [comment]
no, I think use the lane relationship is enough. for example
section0_lane3 -> section1_lane3
                           -> section1_lane4

**Comment by treenewbee213** [comment]
Thanks for the response! But I mean if I want to transform a opendrive file into apollo,  I cannot get such lanes section1_lane3 and section1_lane4. in opendrive, section1_lane3 and section1_lane4 cannot be divided into one section like this, they cannot  overlap, isn't it? If I want to get section1_lane3 and section1_lane4 in apollo, how can I define the two lanes in opendrive?

**Comment by daohu527** [comment]
From the spec
> Lanes may be split into multiple lane sections. Each lane section contains a fixed number of lanes. Every time the number of lanes changes, a new lane section is required, as shown in [Figure 56](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4422&token=e590561f3c39aa2260e5442e29e93f6693d1cccd#fig-459a1b0f-94d0-4712-8f23-45845d5f4998). Lane sections are defined in ascending order along the road reference line.

![image](https://user-images.githubusercontent.com/10419854/220800124-57a8377b-5a5e-42d9-8f3c-3e02bc2a5788.png)

**Comment by treenewbee213** [comment]
Thanks! But maybe you still mistook my mean. Whatever, I have changed the raw .xosc file to fit this problem.
