### ISSUE TITLE
carla map to apollo bin

### ISSUE THREAD

**Issue by lpxiangyan9** [daohu527/imap#74]
use  imap -f -i Town03.xodr t  -o   apollo_map.txt
throw Exception :TypeError

**Comment by daohu527** [comment]
Can you describe the error message in detail?

**Comment by lpxiangyan9** [comment]
> Can you describe the error message in detail?

imap:5374): GLib-GIO-CRITICAL **: 12:16:35.602: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
parse_geo_reference is +proj=tmerc +lat_0=0 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +geoidgrids=egm96_15.gtx +vunits=m +no_defs : 
Traceback (most recent call last):
  File "/usr/local/bin/imap", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/imap/main.py", line 108, in main
    convert_map_format(args.input, args.output)
  File "/usr/local/lib/python3.8/dist-packages/imap/main.py", line 34, in convert_map_format
    opendrive2apollo.convert()
  File "/usr/local/lib/python3.8/dist-packages/imap/lib/convertor.py", line 577, in convert
    self.convert_roads()
  File "/usr/local/lib/python3.8/dist-packages/imap/lib/convertor.py", line 530, in convert_roads
    pb_last_right_section = self.convert_lane(xodr_road, pb_road)
  File "/usr/local/lib/python3.8/dist-packages/imap/lib/convertor.py", line 436, in convert_lane
    pb_lane = self.create_lane(xodr_road, lane_section, idx, lane)
  File "/usr/local/lib/python3.8/dist-packages/imap/lib/convertor.py", line 380, in create_lane
    self.add_basic_info(pb_lane, xodr_road, idx, lane)
  File "/usr/local/lib/python3.8/dist-packages/imap/lib/convertor.py", line 168, in add_basic_info
    pb_lane.type = to_pb_lane_type(lane.lane_type)
TypeError: None has type NoneType, but expected one of: int, long

**Comment by daohu527** [comment]
Since the map does not have a lane_type, but we need lane_type to generate the lane.

The specification does not require that there must be a type field, I'm not sure if this is good or bad, I will add a default type to solve this problem

**Comment by lpxiangyan9** [comment]
> 
tks to slove this.
becase the map is carla's map,so i think this problem is important. 
Can you send a message after the repair

**Comment by daohu527** [comment]
https://github.com/daohu527/imap/blob/70664c4474a70e7e3827561ccfd91e0deb9a05c2/imap/lib/opendrive/lanes.py#L184

change to
```
  def parse_from(self, raw_lane):
    self.lane_id = raw_lane.attrib.get('id')
    self.lane_type = raw_lane.attrib.get('type')
    if self.lane_type is None:
      self.lane_type = "driving"
```

**Comment by lpxiangyan9** [comment]
> 

I have another question. Can the traffic lights be switched and displayed?

**Comment by daohu527** [comment]
No, I just add traffic light stop line, the total function still underdeveloped.

**Comment by lpxiangyan9** [comment]
> No, I just add traffic light stop line, the total function still underdeveloped.

When will it be added?

**Comment by daohu527** [comment]
not sure, maybe before April.
