### ISSUE TITLE
Potential bugs about road conversion 

### ISSUE THREAD

**Issue by yutong-xie** [daohu527/imap#75]
I use imap to convert town.xodr to apollo map and run the sim control simulation. However, I found that the vehicle cannot drive from **road_9_lane_0_1 s: 15.5023 x: 129.486 y: -55.733** to **road_22_lane_0_-1 s: 26.524 x: 88.7576 y: -94.6779**, cause these will be a gap in the planned route. 
![gap](https://user-images.githubusercontent.com/36655655/224266584-d0a2f181-5434-45d0-b6a4-b82c282ea862.png)

And I check the generated base_map.txt file, I found that the length of center_line, left_boundary, right_boundary for road_192_lane_0_-1 are the same, which is not as expected. 

I try to increase the length of center_line and right_boundary, and the problem can be fixed. 

I am not sure whether it is a bug of imap, can could you plz pay attention for this issue and solve it fundamentally? Thx in advance.

**Comment by daohu527** [comment]
I also noticed this kind of problem, but i don't understand what you said
> I found that the length of center_line, left_boundary, right_boundary for road_192_lane_0_-1 are the same, which is not as expected.

Normally, shouldn't they be equal? Although the lengths are different, the starting point and the ending point should be the same

do you use the data in imap/data/town.xodr

**Comment by yutong-xie** [comment]
Thanks for your response.

**Comment by yutong-xie** [comment]
Thanks for your response.

I think the length of center_line, left_bounday, and right_boundary should be equal or similar for most of the roads, but not for the road with large curvature. As I showed in the following figure, the **road 192** in town.xodr is a curve and we can see the length for left and right boundary are totally different. Hence, I think we cannot easily assign the length of center line, left/right boundary as the same during the conversion. It may cause the **gap** phenomenon as I said in the origin post, because the center line will be longer than the left boundary. 
![image](https://user-images.githubusercontent.com/36655655/224461080-c35b666e-6585-4196-9ee7-cbb05099ff9b.png)

> do you use the data in imap/data/town.xodr

Yes. All things I mentioned above are relevant to town.xodr.

**Comment by daohu527** [comment]
@yutong-xie I figured it out, I'll debug the routing until I can confirm the problem, then I'll fix it.

**Comment by yutong-xie** [comment]
Thanks so much for your work!
