### ISSUE TITLE
Command 'imap' not found, but there are 15 similar ones.

### ISSUE THREAD

**Issue by ccaptain-Jack-Sparrow** [daohu527/imap#79]
How should this problem be solved？
![2023-04-06 15-23-43屏幕截图](https://user-images.githubusercontent.com/101320438/230304491-9fe5278f-7b44-4022-bf57-0ee30ac23f96.png)

**Comment by daohu527** [comment]
do you install the tool? if not you can use below cmd to install
```
pip3 install imap_box
```

**Comment by ccaptain-Jack-Sparrow** [comment]
Yes, I installed the tool 




| |
郝璐璐
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 04/6/2023 17:22 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [daohu527/imap] Command 'imap' not found, but there are 15 similar ones. (Issue #79) |

do you install the tool? if not you can use below cmd to install

pip3 install imap_box

**Comment by daohu527** [comment]
I don't know why, it looks like you may have installed to the user directory, you can add path use below cmd
```
export PATH=./.local/bin/:$PATH
```
