### ISSUE TITLE
Missing input length check at `imap.imap.lib.convertor.Opendrive2Apollo.add_lane_sample`

### ISSUE THREAD

**Issue by xqgex** [daohu527/imap#85]
## Version

```bash
$ python3 -m pip show imap_box | grep Version
Version: 0.1.6
```

## Traceback

```python
...
    total_s = lane.center_line[0].s
IndexError: list index out of range
```

## Fix

https://github.com/daohu527/imap/blob/e4afa8f0cc555f9fd41a8d32b5363f8c74dd7c2a/imap/lib/convertor.py#L260-L263

Check if the list is empty.

## Suggested fix

```python
    total_s = lane.center_line[0].s if lane.center_line else .0
```

**Comment by daohu527** [comment]
@xqgex 

Thank you for your suggestion, I see that you have submitted multiple issues, I will deal with it as soon as possible

**Comment by daohu527** [comment]
This scenario is too extreme, will there be a lane without a center line?
