### ISSUE TITLE
selected point cannot be a routing point 

### ISSUE THREAD

**Issue by WilliaJing** [daohu527/imap#93]
Hi,I changed the map to Carla_town02 map, open the sim control, I cannot select the endpoint,
 and the prompt message is as follows:
![image](https://github.com/daohu527/imap/assets/50048416/9151aa1f-fea5-412a-b667-5fad5157975f)

![image](https://github.com/daohu527/imap/assets/50048416/b64d1e9c-c750-4bbd-8697-499b2351f251)

**Comment by WilliaJing** [comment]
hello,Imap seems to be not very complete. After converting the map using imap, I opened the sim controller in Dreamview and the car couldn't run. I feel like there was a problem with the positioning. 
Should I still choose roadrunner to convert Carla maps to Apollo maps?thank you for your reply.

**Comment by daohu527** [comment]
Honestly roadrunner also has some conversion bugs, you know that's not their main business. of course, you can try it might work.

The error means the point is not the driving direction and heading are wrong. You can try setting points in the opposite direction

**Comment by WilliaJing** [comment]
> Honestly roadrunner also has some conversion bugs, you know that's not their main business. of course, you can try it might work.
> 
> The error means the point is not the driving direction and heading are wrong. You can try setting points in the opposite direction

@daohu527 ok,I'll try more.thanks.
