### ISSUE TITLE
No existing file found in modules/map/data

### ISSUE THREAD

**Issue by WilliaJing** [daohu527/imap#94]
![image](https://github.com/daohu527/imap/assets/50048416/235b152b-3161-4097-9276-1a6b0011e988)

hi,Does anyone know the impact of this error？how to solve?

**Comment by daohu527** [comment]
I'm not sure if this error is normal, you can ref
https://github.com/daohu527/dig-into-apollo/tree/main/questions#map

**Comment by WilliaJing** [comment]
thank you @daohu527 ,Does the successful execution of this Python file indicate successful map conversion
```
python modules/tools/routing/debug_topo.py
```
and,result,
![uTools_1689320727418](https://github.com/daohu527/imap/assets/50048416/765178a9-614e-49cb-b381-e6f40057e8f6)

Can this result prove that the conversion was successful？

**Comment by daohu527** [comment]
no, it's just a tool help to found topo errors. for example you can use the tool to find if lane_0_1 can reach by lane_198_1

**Comment by WilliaJing** [comment]
> no, it's just a tool help to found topo errors. for example you can use the tool to find if lane_0_1 can reach by lane_198_1

ok,thank you. I was Verified,it is not affected.
