### ISSUE TITLE
Error parsing max_speed parameter in xodr file

### ISSUE THREAD

**Issue by meua** [daohu527/imap#98]
The max_speed parsed from the file is all wrong, and the parsed value is 11.176. The content of the Town01.xodr file is as follows：
```xml
    <road name="Road 22" length="5.1689999999999998e+1" id="22" junction="-1">
        <type s="0.0000000000000000e+0" type="town">
            <speed max="25" unit="mph"/>
        </type>
        <lanes>
             ...
        </lanes>
        <objects>
            <object id="436" name="Speed_30" s="4.7350668886646943e+1" t="4.3914420160242855e+0" zOffset="1.5035057067871094e-1" hdg="3.1414406299591064e+0" roll="0.0000000000000000e+0" pitch="0.0000000000000000e+0" orientation="+" type="-1" height="0.0000000000000000e+0" width="0.0000000000000000e+0" length="0.0000000000000000e+0"/>
        </objects>
        <signals>
            ...
        </signals>
    </road>
```

**Comment by daohu527** [comment]
I found that both road and lane have speed limit, since the lack of speed will cause the planning speed to be very slow, I set a relatively large default value, such as 120km/h.

I will check and fix later!

**Comment by meua** [comment]
> I found that both road and lane have speed limit, since the lack of speed will cause the planning speed to be very slow, I set a relatively large default value, such as 120km/h.
> 
> I will check and fix later!

Thanks for your reply, I will try to fix it soon.

**Comment by daohu527** [comment]
You can try https://github.com/daohu527/imap/tree/fix_speed_limit. add the road speed limit

**Comment by meua** [comment]
alright, thank you very much.
